services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_INITDB_ARGS=--locale=fa_IR.utf8
    ports:
      - "127.0.0.1:5432:5432"
  backend:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    command: uwsgi --ini uwsgi.ini
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/usr/src/app/
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data: